In [29]:
import numpy as np

In [37]:
class BAM:
    def __init__(self, input_size, output_size):
        self.weights = np.zeros((output_size, input_size))

    def train(self, input_patterns ,output_patterns):
        for i in range(input_patterns.shape[0]):
            x = input_patterns[i]
            y = output_patterns[i]
            self.weights +=np.outer(y,x)

    def recall_input(self, output_patterns):
        return np.dot(self.weights, output_patterns)

    def recall_output(self, input_patterns):
        return np.dot(self.weights, input_patterns)

In [38]:
input_size = 2
output_size = 2
bam = BAM(input_size, output_size)

In [39]:
bam.weights

array([[0., 0.],
       [0., 0.]])

In [56]:
input_patterns = np.array([[1,-1],[-1,1]])
output_patterns = np.array([[-1,1],[1,-1]])
bam.train(input_patterns, output_patterns)

In [47]:
input_patterns

array([[ 1, -1],
       [-1,  1]])

In [48]:
output_patterns

array([[-1,  1],
       [ 1, -1]])

In [57]:
test_input = np.array([1,-1])
output_recall = bam.recall_output(test_input)
print("Input", test_input)
print("Recalled Output", output_recall)

Input [ 1 -1]
Recalled Output [-12.  12.]


In [59]:
test_output = np.array([-1,1])
input_recall = bam.recall_input(test_output)
print("Input", input_recall)
print("Recalled Output", test_output)

Input [ 12. -12.]
Recalled Output [-1  1]
