In [1]:
import numpy as np

In [15]:
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        self.W1 = np.random.randn(self.input_size, self.hidden_size)
        self.W2 = np.random.randn(self.hidden_size, self.output_size)

    def sigmoid(self, x):
        return 1/(1+np.exp(-x))

    def sigmoid_derivative(self, x):
        return x*(1-x)

    def forward(self, X):
        # Calculate output of hidden layer
        print("Forward Propogation Start")
        print("X :", X,'\n' ,"W1 :",self.W1,'\n')
        
        self.z = np.dot(X, self.W1)
        
        print("z :",self.z,'\n','\n',self.z.shape)
        
        self.z2 = self.sigmoid(self.z)
        
        print('z2 :',self.z2,'\n','\n',self.z2.shape)
        
        # Calculate output of output layer
        self.z3 = np.dot(self.z2, self.W2)
        
        print("z3 :", self.z3,'\n', "W2 :",self.W2,'\n','\n',self.z3.shape)

        
        output = self.sigmoid(self.z3)
        
        
        print("Output :",output,'\n','\n',output.shape)
        print("Forward Propogation End")
        return output

    def backward(self, X, y, output):
        # Calculate the error and derivative of error for output layer
        print("Backward Propogation Start")
        self.output_error = y - output

        print("output error :",self.output_error)
        
        self.output_delta = self.output_error * self.sigmoid_derivative(output)

        print("output delta :",self.output_delta)
        
        # Calculate the error and derivative of error hidden layer
        self.z2_error = self.output_delta.dot(self.W2.T)

        print("z2 error :",self.z2_error)
        
        self.z2_delta = self.z2_error * self.sigmoid_derivative(self.z2)

        print("z2 delta :",self.z2_delta)
        
        # update weights
        self.W1 += X.T.dot(self.z2_delta)

        print("Updated W1 :", self.W1)
        
        self.W2 += self.z2.T.dot(self.output_delta)
        print("Updated W2 :", self.W2)
        print("Backward Propogation End")

    def train(self, X, y, epochs):
        for i in range(epochs):
            # Forward propogation
            output = self.forward(X)

            # Backward propogation
            self.backward(X, y, output)
            print("y :",y)




In [16]:
nn = NeuralNetwork(input_size = 2, hidden_size = 3, output_size = 1)

In [20]:
# Specify train data 'X' anf target output 'y'

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# train the network

nn.train(X, y, epochs=1000)


Forward Propogation Start
X : [[0 0]
 [0 1]
 [1 0]
 [1 1]] 
 W1 : [[ 1.52806494  0.08292637  0.44100473]
 [-0.9734473   0.00788269 -0.0517786 ]] 

z : [[ 0.          0.          0.        ]
 [-0.9734473   0.00788269 -0.0517786 ]
 [ 1.52806494  0.08292637  0.44100473]
 [ 0.55461764  0.09080906  0.38922612]] 
 
 (4, 3)
z2 : [[0.5        0.5        0.5       ]
 [0.27419392 0.50197066 0.48705824]
 [0.82172302 0.52071972 0.60849841]
 [0.63520625 0.52268668 0.59609639]] 
 
 (4, 3)
z3 : [[-0.01558182]
 [ 0.06460175]
 [-0.07086652]
 [-0.00605783]] 
 W2 : [[-0.4017347 ]
 [-0.38456059]
 [ 0.75513166]] 
 
 (4, 1)
Output : [[0.49610462]
 [0.51614482]
 [0.48229078]
 [0.49848555]] 
 
 (4, 1)
Forward Propogation End
Backward Propogation Start
output error : [[-0.49610462]
 [ 0.48385518]
 [ 0.51770922]
 [-0.49848555]]
output delta : [[-0.12401863]
 [ 0.12083767]
 [ 0.12926494]
 [-0.12462024]]
z2 error : [[ 0.04982259  0.04769268 -0.09365039]
 [-0.04854469 -0.04646941  0.09124835]
 [-0.05193021 -0.0497

In [35]:
# Make prediction on new data
new_data = np.array([[0,0],[0,1],[1,0],[1,1]])
predictions = nn.forward(new_data)
print(predictions.round())

Forward Propogation Start
X : [[0 0]
 [0 1]
 [1 0]
 [1 1]] 
 W1 : [[ 6.19338114 -2.90690967  4.72595448]
 [-3.27025636  5.27222754  4.43145193]] 

z : [[ 0.          0.          0.        ]
 [-3.27025636  5.27222754  4.43145193]
 [ 6.19338114 -2.90690967  4.72595448]
 [ 2.92312478  2.36531787  9.15740641]] 
 
 (4, 3)
z2 : [[0.5        0.5        0.5       ]
 [0.03660579 0.99489404 0.98824268]
 [0.99796126 0.05181305 0.9912156 ]
 [0.94897781 0.9141441  0.99989458]] 
 
 (4, 3)
z3 : [[-1.94277996]
 [ 2.41216362]
 [ 2.4042081 ]
 [-2.97315112]] 
 W2 : [[-6.61665007]
 [-6.70667689]
 [ 9.43776703]] 
 
 (4, 1)
Output : [[0.12534277]
 [0.91775015]
 [0.91714763]
 [0.04865366]] 
 
 (4, 1)
Forward Propogation End
[[0.]
 [1.]
 [1.]
 [0.]]
